// Create User
POST http://localhost:5000/users
Content-Type: application/json

{
    "username" : "RizalKun",
    "email" : "PambudiW@gmail.com",
    "password" : "123",
    "confPassword" : "123"
}

###

// Get All User
GET http://localhost:5000/users

###
// Create Category
POST http://localhost:5000/category
Content-Type: application/json

{
    "name" : "BPJS",
    "type" : "income"
}

###
// Get All Category
GET http://localhost:5000/category

###

// Get Category By ID
GET http://localhost:5000/category/e87c31af-9a3a-4196-938d-3da0ea99096c

###
// Update Category by id
PATCH  http://localhost:5000/category/f0b2e0fe-e6bc-4fba-87ae-9458c5cba35a
Content-Type: application/json

{
    "name" : "Bpjs",
    "type" : "expense"
}

###
// Delete Category By ID
DELETE http://localhost:5000/category/f0b2e0fe-e6bc-4fba-87ae-9458c5cba35a

###
// Create Transaction
POST http://localhost:5000/transactions
Content-Type: application/json

{
    "amount" : 100000,
    "type" : "expense",
    "is_scheduled" : "false",
    "category_name" : "Bensin"
}

###
// Get All Transactions
GET http://localhost:5000/transactions

###
// Get Transaction By ID
GET http://localhost:5000/transactions/df327c1a-0032-479d-a61a-aace15d29f46

###
// Update Transaction By ID
PATCH http://localhost:5000/transactions/9f2921dd-621e-4d84-ae13-f3df1594d7a8
Content-Type: application/json

{
    "amount" : 90000,
    "category_name" : "Liburan"
    
}

###
// Delete Transaction By ID
DELETE http://localhost:5000/transactions/5d950575-5dfe-4fc5-a37c-65a63aeaf9f7

###
// Create Schedule
POST http://localhost:5000/scheduled
Content-Type: application/json

{
    "amount" : 57000,
    "period" : "weekly",
    "type" : "expense",
    "start_date" : "2025-04-23",
    "end_date" : "2025-06-23",
    "description" : "Jajan Mingguan",
    "category_name" : "Makanan"
}

###
// Get All Scheduled
GET http://localhost:5000/scheduled

###
// Update Scheduled
PATCH http://localhost:5000/scheduled/ff25816a-46e3-42e6-95cd-3b4cbcc60702
Content-Type: application/json

{
    "description": "Jajan minggu depan"
}

###
// Delete Scheduled By ID
DELETE http://localhost:5000/scheduled/ff25816a-46e3-42e6-95cd-3b4cbcc60702

###
// Schedule Filter
GET http://localhost:5000/scheduled?category_id=4

###
// Schedule Filter Date
GET http://localhost:5000/scheduled?start_date=2025-02-12

###
// Login
POST http://localhost:5000/login
Content-Type: application/json

{
    "email" : "PambudiW@gmail.com",
    "password" : "123"
}

###
// Logout
DELETE http://localhost:5000/logout